language: rust
rust:
  - stable
  - beta
  - nightly
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
os:
  - linux
  - osx
  - windows
compiler:
  - gcc
  - clang
jobs:
  allow_failures:
    - rust: nightly
    - rust: beta
  fast_finish: true
script:
  - cargo build --all-features --verbose --workspace
  - cargo test --all-features --verbose --workspace