version: 0.2

phases:
  pre_build:
    commands:
      - rustup default stable
      - echo $CODEBUILD_SOURCE_VERSION
  build:
    commands:
      - echo Build started on `date`
      - cargo build --all-features --verbose
  post_build:
    commands:
      - echo Build completed on `date`
