version: 0.2

phases:
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - rustup default stable
  build:
    commands:
      - echo Build started on `date`
      - cargo build --all-features --verbose
  post_build:
    commands:
      - echo Build completed on `date`
